Repository cloudquery/cq-provider-gcp, pull requests merged in 2022-01, with the labels that each got.

#98 chore: Synced file(s) with cloudquery/.github
  .github/release.yml
  .github/workflows/add_tags.yml
  .github/workflows/doc_validation.yml
  .github/workflows/golang_lint.yml
  .github/workflows/mock_test.yml
  .github/workflows/pr_title.yml
  .github/workflows/release.yml
  .golangci.yml
Labels: chore

#99 feat: Testable Migrations
  .github/workflows/test_migration.yml
  client/testdata/initial_migration.hcl
  client/testing.go
  go.mod
  go.sum
  resources/provider/migrations/1_v0.4.4.down.sql
  resources/provider/migrations/1_v0.4.4.up.sql
  resources/provider/migrations/2_v0.4.8.down.sql
  resources/provider/migrations/2_v0.4.8.up.sql
  resources/provider/migrations/postgres/3_v0.6.0.down.sql
  resources/provider/migrations/postgres/3_v0.6.0.up.sql
  resources/provider/migrations/timescale/3_v0.6.0.down.sql
  resources/provider/migrations/timescale/3_v0.6.0.up.sql
  resources/provider/provider.go
  resources/provider/provider_test.go
  tools/migrations/main.go
Labels: feat

#100 feat: Upgrade SDK v0.7.0
  go.mod
  go.sum
Labels: feat

#101 chore: Synced file(s) with cloudquery/.github
  .github/workflows/cq_fetch.yml
  .github/workflows/int_test.yml
  .github/workflows/lint.yml
  .github/workflows/lint_doc.yml
  .github/workflows/lint_golang.yml
  .github/workflows/test.yml
  .github/workflows/test_migration.yml
  .github/workflows/test_unit.yml
Labels: ignore-for-release
