Repository cloudquery/cq-provider-gcp, pull requests merged in 2022-03, with the labels that each got.

#131 chore: Synced file(s) with cloudquery/.github
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#134 fix: Error classification
  client/client.go
  client/error.go
  client/services.go
  go.mod
  go.sum
Labels: fix

#135 chore: Synced file(s) with cloudquery/.github
  .github/workflows/lint_doc.yml
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
  .github/workflows/test_integration.yml
  .github/workflows/test_unit.yml
Labels: ignore-for-release

#136 chore: Synced file(s) with cloudquery/.github
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#138 chore: Synced file(s) with cloudquery/.github
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#139 chore: Synced file(s) with cloudquery/.github
  .github/workflows/terraform_apply.yml
Labels: ignore-for-release

#140 chore: Synced file(s) with cloudquery/.github
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#141 chore: Synced file(s) with cloudquery/.github
  .github/workflows/terraform_apply.yml
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#117 feat: Configurable retrier
  client/client.go
  client/config.go
  client/retry.go
  client/testing.go
  go.mod
  go.sum
  resources/services/bigquery/bigquery_dataset_tables.go
  resources/services/bigquery/bigquery_datasets.go
  resources/services/cloudfunctions/cloudfunctions_function.go
  resources/services/compute/compute_addresses.go
  resources/services/compute/compute_autoscalers.go
  resources/services/compute/compute_backend_services.go
  resources/services/compute/compute_disk_types.go
  resources/services/compute/compute_disks.go
  resources/services/compute/compute_firewalls.go
  resources/services/compute/compute_forwarding_rules.go
  resources/services/compute/compute_images.go
  resources/services/compute/compute_instances.go
  resources/services/compute/compute_interconnects.go
  resources/services/compute/compute_networks.go
  resources/services/compute/compute_projects.go
  resources/services/compute/compute_ssl_certificates.go
  resources/services/compute/compute_ssl_policies.go
  resources/services/compute/compute_subnetworks.go
  resources/services/compute/compute_target_https_proxies.go
  resources/services/compute/compute_target_ssl_proxies.go
  resources/services/compute/compute_url_maps.go
  resources/services/compute/compute_vpn_gateways.go
  resources/services/dns/dns_managed_zones.go
  resources/services/dns/dns_policies.go
  resources/services/domains/domains_registration.go
  resources/services/iam/iam_roles.go
  resources/services/iam/iam_service_accounts.go
  resources/services/kms/kms_keyrings.go
  resources/services/logging/logging_metrics.go
  resources/services/logging/logging_sinks.go
  resources/services/monitoring/monitoring_alert_policies.go
  resources/services/resource_manager/resource_manager_folders.go
  resources/services/resource_manager/resource_manager_projects.go
  resources/services/sql/sql_instances.go
  resources/services/storage/storage_buckets.go
Labels: feat

#146 chore: Update SDK
  go.mod
  go.sum
Labels: ignore-for-release

#150 fix: Improve error message for misapplied config
  client/client.go
Labels: bug, enhancement

#148 chore: Update from .github
  .github/workflows/README
  .github/workflows/lint_doc.yml
  .github/workflows/lint_golang.yml
  .github/workflows/terraform_apply.yml
  .github/workflows/terraform_plan.yml
  .github/workflows/test_integration.yml
  .github/workflows/test_unit.yml
  CODEOWNERS
  CODE_OF_CONDUCT.md
  scripts/terraform-apply-all.sh
  scripts/terraform-apply-changes-only.sh
  scripts/terraform-fmt-change-only.sh
  scripts/terraform-init-change-only.sh
  scripts/terraform-plan-change-only.sh
  scripts/terraform-validate-all.sh
  scripts/terraform-validate-change-only.sh
Labels: ignore-for-release

#153 feat: Update cq-provider-sdk to v0.8.11
  go.mod
  go.sum
Labels: feat

#155 chore: Sync form .github
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#157 chore: Sync form .github
  .github/workflows/terraform_plan.yml
Labels: ignore-for-release

#156 chore: Delete CODE_OF_CODUCT in favour of org wide
  CODE_OF_CONDUCT.md
Labels: ignore-for-release

#158 test: Test new tf workflow
  .github/workflows/terraform_plan.yml
  .github/workflows/test_integration.yml
  terraform/bigquery/modules/test/providers.tf
Labels: ignore-for-release

#159 chore: Fix checkout for terraform plan forks
  .github/workflows/terraform_plan.yml
  terraform/bigquery/modules/test/providers.tf
Labels: ignore-for-release

#162 chore: Sync form .github
  .github/workflows/terraform_plan.yml
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#163 chore: Sync form .github
  CONTRIBUTING.md
Labels: ignore-for-release

#164 docs: Add 'resources' to config section of docs
  docs/index.md
Labels: docs

#165 chore: Sync form .github
  Makefile
Labels: ignore-for-release

#166 docs: Add contribution guides
  docs/contributing/adding_a_new_resource.md
  docs/contributing/development_environment.md
Labels: docs

#167 docs: Update typo in adding a resource
  docs/contributing/adding_a_new_resource.md
Labels: docs

#168 chore: Sync form .github
  .github/workflows/test_integration.yml
  docs/contributing/issue_reporting.md
Labels: ignore-for-release

#169 test: Fix flaky disk types
  resources/services/compute/compute_disk_types_mock_test.go
Labels: test

#170 fix: Update SDK
  go.mod
  go.sum
Labels: fix

#173 fix: Return diagnostics on failed permissions in storage.Buckets
  client/error.go
  docs/docs.go
  go.mod
  go.sum
  resources/services/storage/storage_buckets.go
Labels: fix

#171 feat: Added new resource gcp_compute_target_http_proxies
  docs/contributing/adding_a_new_resource.md
  docs/tables/gcp_compute_target_http_proxies.md
  resources/provider/migrations/postgres/4_v0.6.6.down.sql
  resources/provider/migrations/postgres/4_v0.6.6.up.sql
  resources/provider/migrations/timescale/4_v0.6.6.down.sql
  resources/provider/migrations/timescale/4_v0.6.6.up.sql
  resources/provider/provider.go
  resources/services/compute/compute_target_http_proxies.go
  resources/services/compute/compute_target_http_proxies_mock_test.go
  terraform/compute/local/main.tf
  terraform/compute/local/variables.tf
  terraform/compute/modules/test/backend.tf
  terraform/compute/modules/test/compute_backend.tf.backup
  terraform/compute/modules/test/ssl.tf
  terraform/compute/modules/test/url_maps.tf
Labels: feat

#176 chore: Update SDK
  go.mod
  go.sum
Labels: ignore-for-release
