Repository cloudquery/cq-provider-gcp, pull requests merged in 2022-05, with the labels that each got.

#215 fix: Configure classification about access
  client/error.go
Labels: fix

#227 chore(deps): Delete `dependabot.yml`
  .github/dependabot.yml
Labels: ignore-for-release

#221 chore(release): Add release PR flow
  .github/workflows/release-please.yml
Labels: ignore-for-release

#219 chore: Added instance groups management tf
  terraform/compute/modules/test/instance_groups.tf
Labels: ignore-for-release

#239 feat: Billing resources
  client/services.go
  docs/tables/gcp_cloudbilling_accounts.md
  docs/tables/gcp_cloudbilling_service_sku_pricing_info.md
  docs/tables/gcp_cloudbilling_service_sku_pricing_info_tiered_rates.md
  docs/tables/gcp_cloudbilling_service_skus.md
  docs/tables/gcp_cloudbilling_services.md
  resources/provider/migrations/postgres/7_v0.7.2.down.sql
  resources/provider/migrations/postgres/7_v0.7.2.up.sql
  resources/provider/migrations/timescale/7_v0.7.2.down.sql
  resources/provider/migrations/timescale/7_v0.7.2.up.sql
  resources/provider/provider.go
  resources/services/cloudbilling/accounts.go
  resources/services/cloudbilling/accounts_mock_test.go
  resources/services/cloudbilling/gen.hcl
  resources/services/cloudbilling/services.go
  resources/services/cloudbilling/services_mock_test.go
Labels: feat

#233 test: Add cq-config for policy test
  test/policy_cq_config.hcl
Labels: test

#270 chore: Reduce compute cost
  terraform/compute/modules/test/instances.tf
Labels: automerge

#275 chore(terraform-container): Fix typo
  terraform/container/prod/terraform.tf
Labels: automerge

#276 chore: Fix style issues
  client/client.go
  client/config.go
  client/error.go
  client/resolvers.go
  client/retry.go
  docs/docs.go
  resources/provider/provider.go
  resources/services/bigquery/bigquery_dataset_accesses.go
  resources/services/bigquery/bigquery_dataset_tables.go
  resources/services/cloudbilling/accounts.go
  resources/services/compute/compute_addresses.go
  resources/services/compute/compute_addresses_mock_test.go
  resources/services/compute/compute_autoscalers.go
  resources/services/compute/compute_autoscalers_mock_test.go
  resources/services/compute/compute_backend_services.go
  resources/services/compute/compute_disk_types.go
  resources/services/compute/compute_instances_mock_test.go
  resources/services/compute/compute_interconnects_mock_test.go
  resources/services/compute/compute_projects_mock_test.go
  resources/services/compute/compute_ssl_certificates_mock_test.go
  resources/services/compute/compute_ssl_policies_mock_test.go
  resources/services/compute/compute_subnetworks_mock_test.go
  resources/services/compute/compute_target_http_proxies_mock_test.go
  resources/services/compute/compute_target_https_proxies_mock_test.go
  resources/services/compute/compute_target_ssl_proxies_mock_test.go
  resources/services/compute/compute_url_maps_mock_test.go
  resources/services/compute/compute_vpn_gateways_mock_test.go
  resources/services/domains/domains_registration.go
  resources/services/kms/kms_keyrings.go
  resources/services/storage/storage_metrics.go
Labels: automerge

#267 feat: Add GKE clusters
  client/error.go
  client/services.go
  docs/tables/gcp_kubernetes_cluster_node_pools.md
  docs/tables/gcp_kubernetes_clusters.md
  resources/provider/provider.go
  resources/services/kubernetes/clusters.go
  resources/services/kubernetes/clusters_mock_test.go
  resources/services/kubernetes/gen.hcl
  terraform/kubernetes/local/main.tf
  terraform/kubernetes/local/variables.tf
  terraform/kubernetes/modules/test/account.tf
  terraform/kubernetes/modules/test/cluster.tf
  terraform/kubernetes/modules/test/network.tf
  terraform/kubernetes/modules/test/providers.tf
  terraform/kubernetes/modules/test/variables.tf
  terraform/kubernetes/prod/.terraform.lock.hcl
  terraform/kubernetes/prod/main.tf
  terraform/kubernetes/prod/terraform.tf
Labels: automerge
