Repository cloudquery/cq-provider-gcp, pull requests merged in 2022-02, with the labels that each got.

#105 docs: Fix out-of-date example query in docs
  docs/index.md
Labels: docs

#108 fix: Update SDK, redact errors
  client/error.go
  client/error_test.go
  go.mod
  go.sum
Labels: fix

#111 chore: Run all unittests in parallel (including migrations)
  .github/workflows/test_migration.yml
  resources/provider/provider_test.go
Labels: ignore-for-release

#109 refactor: Drop Crm (take two)
  client/services.go
Labels: refactor

#113 chore: Synced file(s) with cloudquery/.github
  .github/dependabot.yml
Labels: ignore-for-release

#114 feat: Update sdk to v0.7.8 (support max_goroutines config)
  go.mod
  go.sum
Labels: feat

#115 feat: Update SDK for diag handling
  client/error.go
  go.mod
  go.sum
Labels: feat

#119 docs: Copy 'Authentication' section from 'Getting-Started' guide
  docs/index.md
Labels: docs

#122 chore: Add echo to debug int workflow
  .github/workflows/test_integration.yml
Labels: ignore-for-release

#116 chore: Synced file(s) with cloudquery/.github
  .github/dependabot.yml
Labels: ignore-for-release

#130 chore: Synced file(s) with cloudquery/.github
  .github/dependabot.yml
  .github/release.yml
  .github/workflows/test_integration.yml
Labels: ignore-for-release
