Repository cloudquery/cq-provider-gcp, pull requests merged in 2022-04, with the labels that each got.

#178 feat: Add support for storage metrics
  docs/tables/gcp_storage_metrics.md
  resources/provider/migrations/postgres/5_v0.6.7.down.sql
  resources/provider/migrations/postgres/5_v0.6.7.up.sql
  resources/provider/migrations/timescale/5_v0.6.7.down.sql
  resources/provider/migrations/timescale/5_v0.6.7.up.sql
  resources/provider/provider.go
  resources/services/storage/storage_metrics.go
Labels: feat

#179 fix: GCP retrier infinite loop
  client/client.go
  client/config.go
  client/retry.go
Labels: fix

#181 feat: Added bucket encryption type
  docs/tables/gcp_storage_buckets.md
  resources/provider/migrations/postgres/6_v0.6.8.down.sql
  resources/provider/migrations/postgres/6_v0.6.8.up.sql
  resources/provider/migrations/timescale/6_v0.6.8.down.sql
  resources/provider/migrations/timescale/6_v0.6.8.up.sql
  resources/services/storage/storage_buckets.go
Labels: feat

#190 feat: Parallel calls for Big Query dataset
  go.mod
  resources/services/bigquery/bigquery_dataset_tables.go
Labels: feat

#196 chore: Ensure Mock Tests Run
  client/testing.go
Labels: ignore-for-release

#200 feat: Generic DateResolver used to simplify code
  client/resolvers.go
  resources/services/compute/compute_projects.go
  resources/services/compute/compute_ssl_policies.go
  resources/services/compute/compute_target_http_proxies.go
  resources/services/compute/compute_target_https_proxies.go
  resources/services/compute/compute_target_ssl_proxies.go
  resources/services/iam/iam_service_accounts.go
  resources/services/kms/kms_keyrings.go
  resources/services/resource_manager/resource_manager_folders.go
  resources/services/resource_manager/resource_manager_projects.go
Labels: feat

#201 chore: Add local terraform variables
  terraform/bigquery/local/variables.tf
  terraform/cloudfunctions/local/variables.tf
  terraform/dns/local/variables.tf
  terraform/kms/local/variables.tf
  terraform/logging/local/variables.tf
  terraform/monitoring/local/variables.tf
  terraform/sql/local/variables.tf
Labels: ignore-for-release

#188 feat: Get projects in given folders
  client/client.go
  client/client_test.go
  client/config.go
  docs/index.md
Labels: feat

#206 chore: Upgrade SDK to 0.9.1
  client/client.go
  client/error.go
  client/testing.go
  go.mod
  go.sum
Labels: ignore-for-release

#204 chore: Ignore local terraform files
  .gitignore
Labels: ignore-for-release
